### ISSUE TITLE
npm run watch failed

### ISSUE THREAD

**Issue by wulucxy** [jamestthompson3/viiksetjs#5]
error message：
```
> viiksetjs@0.0.24 watch /work/d3/viiksetjs
> babel --watch src --out-dir lib

Successfully compiled 23 files with Babel.
The optional dependency chokidar failed to install and is required for --watch. Chokidar is likely not supported on your platform.
{ Error: Cannot find module 'anymatch'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/work/d3/viiksetjs/node_modules/chokidar/index.js:6:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by wulucxy** [comment]
and I found that change this to below fix this the problem。
```javascript
babel src --out-dir lib --watch
```

I don't know why。

**Comment by jamestthompson3** [comment]
@wulucxy  Thanks for reporting the issue! I can change the default script to that, ( it works for me with `--watch` either in front of the directories or behind ) or you can make a pull request as part of Hacktoberfest.
